package com.pca.bpms.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.remote.Remotable
public class IssueCase implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   private java.lang.Long id;

   // 問題類態
   private java.lang.String issueType;

   // 問題件提交人員
   private java.lang.String sender;

   // 前一次的問題件處理人員
   private java.lang.String handler;

   //private java.util.List<java.lang.String> comment;

   public IssueCase()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getIssueType()
   {
      return this.issueType;
   }

   public void setIssueType(java.lang.String issueType)
   {
      this.issueType = issueType;
   }

   public java.lang.String getSender()
   {
      return this.sender;
   }

   public void setSender(java.lang.String sender)
   {
      this.sender = sender;
   }

   public java.lang.String getHandler()
   {
      return this.handler;
   }

   public void setHandler(java.lang.String handler)
   {
      this.handler = handler;
   }

   //   public java.util.List<java.lang.String> getComment()
   //   {
   //      return this.comment;
   //   }
   //
   //   public void setComment(java.util.List<java.lang.String> comment)
   //   {
   //      this.comment = comment;
   //   }

   public IssueCase(java.lang.Long id, java.lang.String issueType,
         java.lang.String sender, java.lang.String handler)
   {
      this.id = id;
      this.issueType = issueType;
      this.sender = sender;
      this.handler = handler;
   }

}