package com.pca.bpms.model.healthcheckup;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.remote.Remotable
public class Checkup implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   // *處理狀態 (保留)
   private java.lang.String workStatus;

   // *契變號碼
   private java.lang.String changeNo;

   // *是否問題件
   private java.lang.Boolean issueRaised;

   // *被保險人ID
   private java.lang.String inssuredId;

   // 體檢單號碼 (保留)
   private java.lang.String healthNo;

   // 條碼 ===> remove
   //private java.util.List<java.lang.String> barcode;

   // 關卡名稱 ===> remove
   //private java.lang.String taskName;

   // 影像清單 ===> remove
   //private java.util.List<java.lang.String> cmImagelist;

   // 影像caseID ===> remove
   //private java.lang.String caseId;

   // 保單號碼 ===> remove
   //private java.lang.String policyNo;

   // 受理號碼 ===> remove
   //private java.lang.String proposalNo;

   // 存倉號碼 ===> remove
   //private java.lang.String storageNo;

   // 關卡名(中文) ===> remove
   //private java.lang.String taskDesc;

   public Checkup()
   {
   }

   public java.lang.String getWorkStatus()
   {
      return this.workStatus;
   }

   public void setWorkStatus(java.lang.String workStatus)
   {
      this.workStatus = workStatus;
   }

   public java.lang.String getChangeNo()
   {
      return this.changeNo;
   }

   public void setChangeNo(java.lang.String changeNo)
   {
      this.changeNo = changeNo;
   }

   public java.lang.String getHealthNo()
   {
      return this.healthNo;
   }

   public void setHealthNo(java.lang.String healthNo)
   {
      this.healthNo = healthNo;
   }

   public java.lang.String getInssuredId()
   {
      return this.inssuredId;
   }

   public void setInssuredId(java.lang.String inssuredId)
   {
      this.inssuredId = inssuredId;
   }

   public java.lang.Boolean getIssueRaised()
   {
      return this.issueRaised;
   }

   public void setIssueRaised(java.lang.Boolean issueRaised)
   {
      this.issueRaised = issueRaised;
   }

   public Checkup(java.lang.String workStatus, java.lang.String changeNo,
         java.lang.Boolean issueRaised, java.lang.String inssuredId,
         java.lang.String healthNo)
   {
      this.workStatus = workStatus;
      this.changeNo = changeNo;
      this.issueRaised = issueRaised;
      this.inssuredId = inssuredId;
      this.healthNo = healthNo;
   }

}