package com.pca.bpms.model.newbusiness;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.remote.Remotable
public class DataEntry implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean issueRaised;
   private java.lang.Boolean reviewed;
   private java.lang.Boolean divided;
   private java.lang.String creator;
   private java.lang.String reviewer;

   public DataEntry()
   {
   }

   public java.lang.Boolean getIssueRaised()
   {
      return this.issueRaised;
   }

   public void setIssueRaised(java.lang.Boolean issueRaised)
   {
      this.issueRaised = issueRaised;
   }

   public java.lang.Boolean getReviewed()
   {
      return this.reviewed;
   }

   public void setReviewed(java.lang.Boolean reviewed)
   {
      this.reviewed = reviewed;
   }

   public java.lang.Boolean getDivided()
   {
      return this.divided;
   }

   public void setDivided(java.lang.Boolean divided)
   {
      this.divided = divided;
   }

   public java.lang.String getCreator()
   {
      return this.creator;
   }

   public void setCreator(java.lang.String creator)
   {
      this.creator = creator;
   }

   public java.lang.String getReviewer()
   {
      return this.reviewer;
   }

   public void setReviewer(java.lang.String reviewer)
   {
      this.reviewer = reviewer;
   }

   public DataEntry(java.lang.Boolean issueRaised, java.lang.Boolean reviewed,
         java.lang.Boolean divided, java.lang.String creator,
         java.lang.String reviewer)
   {
      this.issueRaised = issueRaised;
      this.reviewed = reviewed;
      this.divided = divided;
      this.creator = creator;
      this.reviewer = reviewer;
   }

}