package com.pca.bpms.model.newbusiness;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.remote.Remotable
public class InquiryLIA implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   //@org.kie.api.definition.type.Label("處理狀態")
   private java.lang.String workStatus;
   //@org.kie.api.definition.type.Label("是否問題件")
   private java.lang.Boolean issueRaised;

   //@org.kie.api.definition.type.Label(value = "\u662F\u5426\u66AB\u4E0D\u8655\u7406")
   private java.lang.Boolean unproced;

   public InquiryLIA()
   {
   }

   public java.lang.String getWorkStatus()
   {
      return this.workStatus;
   }

   public void setWorkStatus(java.lang.String workStatus)
   {
      this.workStatus = workStatus;
   }

   public java.lang.Boolean getIssueRaised()
   {
      return this.issueRaised;
   }

   public void setIssueRaised(java.lang.Boolean issueRaised)
   {
      this.issueRaised = issueRaised;
   }

   public java.lang.Boolean getUnproced()
   {
      return this.unproced;
   }

   public void setUnproced(java.lang.Boolean unproced)
   {
      this.unproced = unproced;
   }

   public InquiryLIA(java.lang.String workStatus, java.lang.Boolean issueRaised,
         java.lang.Boolean unproced)
   {
      this.workStatus = workStatus;
      this.issueRaised = issueRaised;
      this.unproced = unproced;
   }

}