package com.pca.bpms.model.newbusiness;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.remote.Remotable
public class MainControl implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String 通路別;
	private String 銷售單位;
	private String 進件方式;
	private String 案件別;
	private String 首期繳費方式;
	private String 是否繳款成功;
	private String 可預先請授權;
	// private String 再扣款;
	private String 是否核保通過;
	private String 受理;
	private String 建檔;
	private String 建檔覆核;
	private String 公會索引;
	private String 核保前信用卡請授權;
	private String 自動核保;
	private String jetCase;
	private String 核保後信用卡請授權;
	private String 核保照會;
	private String 自動轉帳請款;
	// private String 請授權成功;
	private String 有授權碼;
	// private String 資料匯入;
	// private String 掃描;
	private String 發單處理;

	private String 核保規則;
	private String 核保前匯款報繳;
	private String 核保後匯款報繳;
	private String 核保後待補件;

	public MainControl() {
	}

	/**
	 * @return the 通路別
	 */
	public String get通路別() {
		return 通路別;
	}

	/**
	 * @param 通路別
	 *            the 通路別 to set
	 */
	public void set通路別(String 通路別) {
		this.通路別 = 通路別;
	}

	/**
	 * @return the 銷售單位
	 */
	public String get銷售單位() {
		return 銷售單位;
	}

	/**
	 * @param 銷售單位
	 *            the 銷售單位 to set
	 */
	public void set銷售單位(String 銷售單位) {
		this.銷售單位 = 銷售單位;
	}

	/**
	 * @return the 進件方式
	 */
	public String get進件方式() {
		return 進件方式;
	}

	/**
	 * @param 進件方式
	 *            the 進件方式 to set
	 */
	public void set進件方式(String 進件方式) {
		this.進件方式 = 進件方式;
	}

	/**
	 * @return the 案件別
	 */
	public String get案件別() {
		return 案件別;
	}

	/**
	 * @param 案件別
	 *            the 案件別 to set
	 */
	public void set案件別(String 案件別) {
		this.案件別 = 案件別;
	}

	/**
	 * @return the 首期繳費方式
	 */
	public String get首期繳費方式() {
		return 首期繳費方式;
	}

	/**
	 * @param 首期繳費方式
	 *            the 首期繳費方式 to set
	 */
	public void set首期繳費方式(String 首期繳費方式) {
		this.首期繳費方式 = 首期繳費方式;
	}

	/**
	 * @return the 有授權碼
	 */
	public String get是否繳款成功() {
		return 是否繳款成功;
	}

	/**
	 * @param 有授權碼
	 *            the 有授權碼 to set
	 */
	public void set是否繳款成功(String 是否繳款成功) {
		this.是否繳款成功 = 是否繳款成功;
	}

	/**
	 * @return the 可預先請授權
	 */
	public String get可預先請授權() {
		return 可預先請授權;
	}

	/**
	 * @param 可預先請授權
	 *            the 可預先請授權 to set
	 */
	public void set可預先請授權(String 可預先請授權) {
		this.可預先請授權 = 可預先請授權;
	}

	/**
	 * @return the 是否核保通過
	 */
	public String get是否核保通過() {
		return 是否核保通過;
	}

	/**
	 * @param 是否核保通過
	 *            the 是否核保通過 to set
	 */
	public void set是否核保通過(String 是否核保通過) {
		this.是否核保通過 = 是否核保通過;
	}

	/**
	 * @return the 建檔
	 */
	public String get建檔() {
		return 建檔;
	}

	/**
	 * @param 建檔
	 *            the 建檔 to set
	 */
	public void set建檔(String 建檔) {
		this.建檔 = 建檔;
	}

	/**
	 * @return the 建檔覆核
	 */
	public String get建檔覆核() {
		return 建檔覆核;
	}

	/**
	 * @param 建檔覆核
	 *            the 建檔覆核 to set
	 */
	public void set建檔覆核(String 建檔覆核) {
		this.建檔覆核 = 建檔覆核;
	}

	/**
	 * @return the 公會索引
	 */
	public String get公會索引() {
		return 公會索引;
	}

	/**
	 * @param 公會索引
	 *            the 公會索引 to set
	 */
	public void set公會索引(String 公會索引) {
		this.公會索引 = 公會索引;
	}

	/**
	 * @return the 核保前信用卡請授權
	 */
	public String get核保前信用卡請授權() {
		return 核保前信用卡請授權;
	}

	/**
	 * @param 核保前信用卡請授權
	 *            the 核保前信用卡請授權 to set
	 */
	public void set核保前信用卡請授權(String 核保前信用卡請授權) {
		this.核保前信用卡請授權 = 核保前信用卡請授權;
	}

	/**
	 * @return the 自動核保
	 */
	public String get自動核保() {
		return 自動核保;
	}

	/**
	 * @param 自動核保
	 *            the 自動核保 to set
	 */
	public void set自動核保(String 自動核保) {
		this.自動核保 = 自動核保;
	}

	/**
	 * @return the jetCase
	 */
	public String getJetCase() {
		return jetCase;
	}

	/**
	 * @param jetCase
	 *            the jetCase to set
	 */
	public void setJetCase(String jetCase) {
		this.jetCase = jetCase;
	}

	/**
	 * @return the 核保後信用卡請授權
	 */
	public String get核保後信用卡請授權() {
		return 核保後信用卡請授權;
	}

	/**
	 * @param 核保後信用卡請授權
	 *            the 核保後信用卡請授權 to set
	 */
	public void set核保後信用卡請授權(String 核保後信用卡請授權) {
		this.核保後信用卡請授權 = 核保後信用卡請授權;
	}

	/**
	 * @return the 核保照會
	 */
	public String get核保照會() {
		return 核保照會;
	}

	/**
	 * @param 核保照會
	 *            the 核保照會 to set
	 */
	public void set核保照會(String 核保照會) {
		this.核保照會 = 核保照會;
	}

	/**
	 * @return the 自動轉帳請款
	 */
	public String get自動轉帳請款() {
		return 自動轉帳請款;
	}

	/**
	 * @param 自動轉帳請款
	 *            the 自動轉帳請款 to set
	 */
	public void set自動轉帳請款(String 自動轉帳請款) {
		this.自動轉帳請款 = 自動轉帳請款;
	}

	public String get有授權碼() {
		return 有授權碼;
	}

	public void set有授權碼(String 有授權碼) {
		this.有授權碼 = 有授權碼;
	}

	public String get發單處理() {
		return 發單處理;
	}

	public void set發單處理(String 發單處理) {
		this.發單處理 = 發單處理;
	}

	public String get核保規則() {
		return 核保規則;
	}

	public void set核保規則(String 核保規則) {
		this.核保規則 = 核保規則;
	}

	public String get核保後匯款報繳() {
		return 核保後匯款報繳;
	}

	public void set核保後匯款報繳(String 核保後匯款報繳) {
		this.核保後匯款報繳 = 核保後匯款報繳;
	}

	public String get核保後待補件() {
		return 核保後待補件;
	}

	public void set核保後待補件(String 核保後待補件) {
		this.核保後待補件 = 核保後待補件;
	}

	public String get受理() {
		return 受理;
	}

	public void set受理(String 受理) {
		this.受理 = 受理;
	}
	

	public String get核保前匯款報繳() {
		return 核保前匯款報繳;
	}

	public void set核保前匯款報繳(String 核保前匯款報繳) {
		this.核保前匯款報繳 = 核保前匯款報繳;
	}
	
	

	public MainControl(String 通路別, String 銷售單位, String 進件方式, String 案件別, String 首期繳費方式, String 是否繳款成功, String 可預先請授權,
			String 是否核保通過, String 受理, String 建檔, String 建檔覆核, String 公會索引, String 核保前信用卡請授權, String 自動核保,
			String jetCase, String 核保後信用卡請授權, String 核保照會, String 自動轉帳請款, String 有授權碼, String 發單處理, String 核保規則,
			String 核保前匯款報繳, String 核保後匯款報繳, String 核保後待補件) {
		super();
		this.通路別 = 通路別;
		this.銷售單位 = 銷售單位;
		this.進件方式 = 進件方式;
		this.案件別 = 案件別;
		this.首期繳費方式 = 首期繳費方式;
		this.是否繳款成功 = 是否繳款成功;
		this.可預先請授權 = 可預先請授權;
		this.是否核保通過 = 是否核保通過;
		this.受理 = 受理;
		this.建檔 = 建檔;
		this.建檔覆核 = 建檔覆核;
		this.公會索引 = 公會索引;
		this.核保前信用卡請授權 = 核保前信用卡請授權;
		this.自動核保 = 自動核保;
		this.jetCase = jetCase;
		this.核保後信用卡請授權 = 核保後信用卡請授權;
		this.核保照會 = 核保照會;
		this.自動轉帳請款 = 自動轉帳請款;
		this.有授權碼 = 有授權碼;
		this.發單處理 = 發單處理;
		this.核保規則 = 核保規則;
		this.核保前匯款報繳 = 核保前匯款報繳;
		this.核保後匯款報繳 = 核保後匯款報繳;
		this.核保後待補件 = 核保後待補件;
	}

}