package com.pca.bpms.model.newbusiness;

/**
 * This class was automatically generated by the data modeler tool.
 */

//@org.kie.api.definition.type.Description("是否必須執行子流程之標示用對象")
@org.kie.api.remote.Remotable
public class MustRunSubProcess implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   //@org.kie.api.definition.type.Label("理由")
   private java.lang.String reason;

   public MustRunSubProcess()
   {
   }

   public java.lang.String getReason()
   {
      return this.reason;
   }

   public void setReason(java.lang.String reason)
   {
      this.reason = reason;
   }

   public MustRunSubProcess(java.lang.String reason)
   {
      this.reason = reason;
   }

}