package com.pca.bpms.model.newbusiness;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.remote.Remotable
public class NewContractForm implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String channel;
   private java.lang.String sales;
   private java.lang.String caseInputType;
   private java.lang.String caseKind;
   private java.lang.String payment;
   private java.lang.String paid;
   private java.lang.String vpos;
   private java.lang.String authorized;
   private java.lang.String jetCase;

   public NewContractForm()
   {
   }

   public java.lang.String getChannel()
   {
      return this.channel;
   }

   public void setChannel(java.lang.String channel)
   {
      this.channel = channel;
   }

   public java.lang.String getSales()
   {
      return this.sales;
   }

   public void setSales(java.lang.String sales)
   {
      this.sales = sales;
   }

   public java.lang.String getCaseInputType()
   {
      return this.caseInputType;
   }

   public void setCaseInputType(java.lang.String caseInputType)
   {
      this.caseInputType = caseInputType;
   }

   public java.lang.String getCaseKind()
   {
      return this.caseKind;
   }

   public void setCaseKind(java.lang.String caseKind)
   {
      this.caseKind = caseKind;
   }

   public java.lang.String getPayment()
   {
      return this.payment;
   }

   public void setPayment(java.lang.String payment)
   {
      this.payment = payment;
   }

   public java.lang.String getPaid()
   {
      return this.paid;
   }

   public void setPaid(java.lang.String paid)
   {
      this.paid = paid;
   }

   public java.lang.String getVpos()
   {
      return this.vpos;
   }

   public void setVpos(java.lang.String vpos)
   {
      this.vpos = vpos;
   }

   public java.lang.String getAuthorized()
   {
      return this.authorized;
   }

   public void setAuthorized(java.lang.String authorized)
   {
      this.authorized = authorized;
   }

   public java.lang.String getJetCase()
   {
      return this.jetCase;
   }

   public void setJetCase(java.lang.String jetCase)
   {
      this.jetCase = jetCase;
   }

   public NewContractForm(java.lang.String channel, java.lang.String sales,
         java.lang.String caseInputType, java.lang.String caseKind,
         java.lang.String payment, java.lang.String paid, java.lang.String vpos,
         java.lang.String authorized, java.lang.String jetCase)
   {
      this.channel = channel;
      this.sales = sales;
      this.caseInputType = caseInputType;
      this.caseKind = caseKind;
      this.payment = payment;
      this.paid = paid;
      this.vpos = vpos;
      this.authorized = authorized;
      this.jetCase = jetCase;
   }

}